### PR TITLE
changed registration.compat.patters to list for Django 1.9+ compatibi…

### PR DESCRIPTION
**Pull request by ryanjdillon**
Per #64 

I removed the import of `registration.compat.patterns`, and changed `urlpatterns = patterns(`... to `urlpatterns = [`...

Tested, is working, and errors are now gone.

### CODE REVIEW

**Comment by lambdalisue** [comment]
I'm sorry but it's not acceptable while this PR breaks a backward compatibility.

**Comment by theilgaard** [comment]
How does it break backward compatibility, doesn't it just decrease the test coverage?

**Comment by lambdalisue** [comment]
As far as I know, old Django does not understand this way.

**Comment by ryanjdillon** [comment]
Would it be silly to check django's version and implement the appropriate version with a conditional?

http://stackoverflow.com/q/6468397/943773

**Comment by lambdalisue** [comment]
Using `ImportError` is a bit better but it's ok to check django's version as well.
See https://github.com/lambdalisue/django-inspectional-registration/blob/master/src/registration/compat.py

**Pull request closed without merging**
